version: '3.9'
services:
  node:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: node-container
    ports:
      - '4000:4000'
    volumes:
      - ./node:/app
      - ./app/node_modules
  react:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react-container
    ports:
      - '3000:3000'
    stdin_open: true