version: '3.3'
services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-container
    ports:
      - '9000:9000'
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-container
    ports:
      - '3000:3000'
    stdin_open: true