version: '3.9'
services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-container
    ports:
      - '4000:4000'
    volumes:
      - ./node:/app
      - ./app/node_modules
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-container
    ports:
      - '3000:3000'
    volumes:
      - ./node:/app
      - ./app/node_modules
    stdin_open: true